title: Settings
data:
  site_name: Tworeach
  site_logo: logo.svg
  personality: casual
  show_signup: false
  social:
    -
      id: OoC8w97J
      name: Twitter
      url: 'https://twitter.com/statamic'
      icon: site/social-icons/twitter.svg
    -
      id: Tu52S7O5
      name: Github
      url: 'https://github.com/statamic/starter-kit-starters-creek'
      icon: site/social-icons/github.svg
    -
      id: SZNwm0Sj
      name: Email
      url: 'mailto:jack@statamic.com'
      icon: site/social-icons/email.svg
